import Head from "next/head";
import styles from "../styles/Home.module.scss";



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <div>
      <h1>Welcome to Next.js!</h1>
        <nav className="rounded-sm p-6 bg-gray-400">
          <ul className="flex items-center justify-evenly text-base text-gray-700 pt-4 lg:pt-0">
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
            <li>FAQ</li>
          </ul>
        </nav>
      </div>

      <main className={styles.main}>
        <div className={styles.grid}></div>
        <p>Get started by editing</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
